Revert "(WIP) minimize"
Because of

    java.lang.NoClassDefFoundError: org/jetbrains/kotlin/js/descriptorUtils/DescriptorUtilsKt
    at org.sonarsource.kotlin.checks.VoidShouldBeUnitCheckKt.isJavaLangVoid(VoidShouldBeUnitCheck.kt:114)

And

    java.util.ServiceConfigurationError:
    org.jetbrains.kotlin.resolve.jvm.jvmSignature.KotlinToJvmSignatureMapper:
    Provider org.jetbrains.kotlin.codegen.signature.KotlinToJvmSignatureMapperImpl not found